version: "3.7"
services:
  #
  # postgres
  #
  db:
    container_name: db
    image: postgres:12.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
  #
  # nginx
  #
  nginx:
    container_name: nginx
    image: nginx:1.17.4-alpine
    ports:
      - '8080:8080'
    links:
      - php
    volumes:
      - ../:/srv/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  #
  # php-fpm v7.4
  #
  php:
    container_name: php
    working_dir: /srv
    environment:
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
    volumes:
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
      - ../:/srv/test
    links:
      - db
    build:
      context: php
      dockerfile: 'Dockerfile'
